#!/bin/sh
set -e

ln -s /etc/nginx/sites-available/nginx-airpi-control /etc/nginx/sites-enabled/nginx-airpi-control
rm -f /etc/nginx/sites-enabled/default
/usr/sbin/nginx -s reload

adduser www-data video
chown www-data.www-data /usr/share/airpi-control/site/config.xml

adduser pi tty
systemctl disable serial-getty@ttyAMA0.service
systemctl mask serial-getty@ttyAMA0.service
systemctl stop serial-getty@ttyAMA0.service

pip install --upgrade droneapi pymavlink MAVProxy

